# Use Dockerized infrastructure
sudo: false
language: python
# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/gcloud/"
env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin PYTHONPATH=${HOME}/gcloud/google-cloud-sdk/platform/google_appengine
before_install:
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_40ce2f227d45_key -iv $encrypted_40ce2f227d45_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
# If the SDK is not already cached, download it and unpack it
- tar -xzf credentials.tar.gz
- mkdir -p lib
# Here we use the decrypted service account credentials to authenticate the command line tool
install:
# Set the correct project to deploy to
- gcloud config set project continuous-deployment-python
# Install the AppEngine SDk
- gcloud -q components update gae-python
# Install the Python dependencies
- pip install -r requirements.txt -t lib/
script:
- echo "success"
deploy: 
    provider: gae
    keyfile: client-secret.json
    project: continuous-deployment-python
    version: test
    branch: appengine
