sudo: false
language: python
cache:
  directories:
  - "$HOME/gcloud/"
env:
- PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin PYTHONPATH=${HOME}/gcloud/google-cloud-sdk/platform/google_appengine
before_install:
- openssl aes-256-cbc -K $encrypted_40ce2f227d45_key -iv $encrypted_40ce2f227d45_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set compute/zone us-central1-b
- gcloud config set project continuous-deployment-python
- gcloud -q components update gae-python
- pip install -r requirements.txt -t lib/
script:
- echo "success"
deploy:
  provider: gae
  default: true
  keyfile: client-secret.json
  edge: true
  project: continuous-deployment-python
